# Version 3.4 is is the highest version supported by ubuntu-bundled docker
version: "3.4"
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 8080:8080
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    environment:
      - APP_ENV=dev
      - APP_SECRET=21237091202acfd1399e96e5ccea2ffd
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@database:3306/${BACKEND_DB_NAME}
  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
    ports:
    - 3306:3306

